// Built-in word packs. Each pair contains related but different clue words.
// Loaded before app.js and cached locally for offline play.
const DEFAULT_PAIRS = {
  "Everyday": [
    ["Coffee", "Tea"],
    ["Fork", "Spoon"],
    ["Shower", "Bath"],
    ["Shoes", "Slippers"],
    ["Pillow", "Blanket"],
    ["Phone", "Laptop"],
    ["Door", "Window"],
    ["Pen", "Pencil"],
    ["Soap", "Shampoo"],
    ["Towel", "Tissue"],
    ["Backpack", "Suitcase"],
    ["Wallet", "Purse"],
    ["Watch", "Clock"],
    ["Sofa", "Armchair"],
    ["Plate", "Bowl"],
    ["Cup", "Glass"],
    ["Broom", "Mop"],
    ["Fridge", "Freezer"],
    ["Oven", "Microwave"],
    ["Mirror", "Camera"],
    ["Curtains", "Blinds"],
    ["Key", "Password"],
    ["Stairs", "Lift"],
    ["Bicycle", "Scooter"],
    ["Bus", "Train"],
    ["Umbrella", "Raincoat"],
    ["Socks", "Gloves"],
    ["Notebook", "Diary"],
    ["Comb", "Hairbrush"],
    ["Candle", "Lamp"]
  ],
  "Food": [
    ["Pizza", "Burger"],
    ["Sushi", "Dumpling"],
    ["Pancake", "Waffle"],
    ["Ketchup", "Mustard"],
    ["Lemon", "Lime"],
    ["Cake", "Pie"],
    ["Rice", "Noodles"],
    ["Apple", "Pear"],
    ["Bread", "Toast"],
    ["Butter", "Cheese"],
    ["Honey", "Jam"],
    ["Chocolate", "Caramel"],
    ["Ice cream", "Frozen yogurt"],
    ["Cookie", "Brownie"],
    ["Muffin", "Cupcake"],
    ["Peach", "Apricot"],
    ["Strawberry", "Raspberry"],
    ["Watermelon", "Melon"],
    ["Potato", "Sweet potato"],
    ["Broccoli", "Cauliflower"],
    ["Carrot", "Radish"],
    ["Onion", "Garlic"],
    ["Peanut", "Almond"],
    ["Popcorn", "Potato chips"],
    ["Soup", "Stew"],
    ["Omelette", "Scrambled eggs"],
    ["Croissant", "Bagel"],
    ["Milkshake", "Smoothie"],
    ["Sausage", "Bacon"],
    ["Spaghetti", "Macaroni"]
  ],
  "Places": [
    ["Beach", "Pool"],
    ["School", "Office"],
    ["Airport", "Station"],
    ["Cinema", "Theatre"],
    ["Museum", "Library"],
    ["Hotel", "Hospital"],
    ["Zoo", "Aquarium"],
    ["Forest", "Jungle"],
    ["Cafe", "Restaurant"],
    ["Bakery", "Sweet shop"],
    ["Park", "Garden"],
    ["Mountain", "Hill"],
    ["Lake", "Pond"],
    ["River", "Canal"],
    ["Island", "Peninsula"],
    ["Village", "Town"],
    ["City", "Suburb"],
    ["Market", "Supermarket"],
    ["Castle", "Palace"],
    ["Cabin", "Cottage"],
    ["Bedroom", "Living room"],
    ["Kitchen", "Dining room"],
    ["Balcony", "Terrace"],
    ["Garage", "Car park"],
    ["Gym", "Stadium"],
    ["Farm", "Orchard"],
    ["Desert", "Savanna"],
    ["Cave", "Tunnel"],
    ["Harbour", "Marina"],
    ["Playground", "Theme park"]
  ],
  "Animals": [
    ["Cat", "Dog"],
    ["Lion", "Tiger"],
    ["Shark", "Dolphin"],
    ["Frog", "Toad"],
    ["Bee", "Wasp"],
    ["Rabbit", "Hamster"],
    ["Eagle", "Owl"],
    ["Crocodile", "Alligator"],
    ["Bear", "Panda"],
    ["Horse", "Donkey"],
    ["Sheep", "Goat"],
    ["Cow", "Buffalo"],
    ["Duck", "Goose"],
    ["Chicken", "Turkey"],
    ["Penguin", "Puffin"],
    ["Seal", "Sea lion"],
    ["Whale", "Orca"],
    ["Octopus", "Squid"],
    ["Crab", "Lobster"],
    ["Butterfly", "Moth"],
    ["Ant", "Termite"],
    ["Snail", "Slug"],
    ["Turtle", "Tortoise"],
    ["Lizard", "Gecko"],
    ["Wolf", "Fox"],
    ["Deer", "Moose"],
    ["Monkey", "Gorilla"],
    ["Squirrel", "Chipmunk"],
    ["Hedgehog", "Porcupine"],
    ["Zebra", "Giraffe"]
  ],
  "Wild card": [
    ["Moon", "Sun"],
    ["Wedding", "Funeral"],
    ["Dream", "Nightmare"],
    ["Hero", "Villain"],
    ["Rich", "Famous"],
    ["Ghost", "Zombie"],
    ["Past", "Future"],
    ["Truth", "Dare"],
    ["Magic", "Science"],
    ["Luck", "Skill"],
    ["Secret", "Rumour"],
    ["Wish", "Promise"],
    ["Treasure", "Prize"],
    ["King", "Queen"],
    ["Pirate", "Knight"],
    ["Detective", "Spy"],
    ["Robot", "Alien"],
    ["Mermaid", "Fairy"],
    ["Dragon", "Unicorn"],
    ["Adventure", "Holiday"],
    ["Birthday", "Anniversary"],
    ["Applause", "Cheering"],
    ["Whisper", "Murmur"],
    ["Shadow", "Reflection"],
    ["Sunrise", "Sunset"],
    ["Thunder", "Lightning"],
    ["Rainbow", "Aurora"],
    ["Puzzle", "Riddle"],
    ["Memory", "Imagination"],
    ["Freedom", "Privacy"]
  ],
  "Cozy things": [
    ["Teddy bear", "Plush bunny"],
    ["Duvet", "Quilt"],
    ["Beanbag", "Cushion"],
    ["Pyjamas", "Dressing gown"],
    ["Mittens", "Hand warmers"],
    ["Fireplace", "Heater"],
    ["Hot chocolate", "Warm milk"],
    ["Knitting", "Crochet"],
    ["Scrapbook", "Photo album"],
    ["Bookmark", "Book cover"],
    ["Fairy lights", "Lantern"],
    ["Nap", "Lie-in"],
    ["Picnic", "Barbecue"],
    ["Treehouse", "Tent"],
    ["Hammock", "Swing"],
    ["Music box", "Snow globe"],
    ["Sticker", "Stamp"],
    ["Ribbon", "Bow"],
    ["Yarn", "Thread"],
    ["Embroidery", "Cross stitch"],
    ["Teapot", "Kettle"],
    ["Bubble bath", "Foot bath"],
    ["Slipper socks", "Fuzzy slippers"],
    ["Rocking chair", "Porch swing"],
    ["Scented candle", "Incense"],
    ["Fluffy rug", "Bath mat"],
    ["Rain sounds", "Ocean sounds"],
    ["Bedtime story", "Lullaby"],
    ["Woolly hat", "Scarf"],
    ["Patchwork", "Quilting"]
  ],
  "Activities": [
    ["Swimming", "Diving"],
    ["Running", "Jogging"],
    ["Hiking", "Climbing"],
    ["Cycling", "Skating"],
    ["Skiing", "Snowboarding"],
    ["Surfing", "Paddleboarding"],
    ["Football", "Rugby"],
    ["Tennis", "Badminton"],
    ["Basketball", "Netball"],
    ["Bowling", "Golf"],
    ["Yoga", "Pilates"],
    ["Dancing", "Gymnastics"],
    ["Singing", "Humming"],
    ["Drawing", "Painting"],
    ["Reading", "Writing"],
    ["Cooking", "Baking"],
    ["Fishing", "Crabbing"],
    ["Camping", "Glamping"],
    ["Shopping", "Browsing"],
    ["Gardening", "Flower arranging"],
    ["Photography", "Filming"],
    ["Chess", "Checkers"],
    ["Hide and seek", "Tag"],
    ["Karaoke", "Concert"],
    ["Board game", "Card game"],
    ["Pottery", "Sculpting"],
    ["Juggling", "Magic tricks"],
    ["Origami", "Paper cutting"],
    ["Kayaking", "Canoeing"],
    ["Meditation", "Stretching"]
  ],
  "Singapore treats": [
    ["Kaya toast", "French toast"],
    ["Kopi", "Teh"],
    ["Laksa", "Curry noodles"],
    ["Chicken rice", "Duck rice"],
    ["Satay", "Kebab"],
    ["Roti prata", "Naan"],
    ["Nasi lemak", "Nasi briyani"],
    ["Char kway teow", "Hokkien mee"],
    ["Chilli crab", "Pepper crab"],
    ["Bak kut teh", "Beef soup"],
    ["Popiah", "Spring roll"],
    ["Chwee kueh", "Soon kueh"],
    ["Ondeh ondeh", "Mochi"],
    ["Ice kacang", "Chendol"],
    ["Tau huay", "Pudding"],
    ["Curry puff", "Samosa"],
    ["Fish ball", "Meatball"],
    ["Wanton mee", "Ban mian"],
    ["Mee rebus", "Mee siam"],
    ["Otah", "Fish cake"],
    ["Soya milk", "Almond milk"],
    ["Sugarcane juice", "Coconut water"],
    ["Bandung", "Rose tea"],
    ["Durian", "Jackfruit"],
    ["Mangosteen", "Rambutan"],
    ["Longan", "Lychee"],
    ["Pandan cake", "Butter cake"],
    ["Pineapple tart", "Jam tart"],
    ["Bee hoon", "Glass noodles"],
    ["Youtiao", "Churros"]
  ]
};

// Independently curated Simplified Chinese packs; keys match the English categories.
const CHINESE_PAIRS = {
  "Everyday": [["牙刷", "牙膏"], ["拖鞋", "凉鞋"], ["雨伞", "雨衣"], ["冰箱", "空调"], ["洗衣机", "烘干机"], ["电饭锅", "高压锅"], ["筷子", "勺子"], ["枕头", "被子"], ["书包", "行李箱"], ["手机", "平板电脑"], ["钥匙", "门卡"], ["扫把", "拖把"]],
  "Food": [["包子", "馒头"], ["饺子", "馄饨"], ["豆浆", "牛奶"], ["火锅", "麻辣烫"], ["油条", "麻花"], ["汤圆", "元宵"], ["粽子", "月饼"], ["烧卖", "小笼包"], ["米饭", "粥"], ["煎饼", "葱油饼"], ["红豆", "绿豆"], ["红薯", "土豆"]],
  "Places": [["茶馆", "咖啡馆"], ["菜市场", "超市"], ["故宫", "长城"], ["学校", "图书馆"], ["动物园", "水族馆"], ["海边", "游泳池"], ["公园", "花园"], ["机场", "火车站"], ["电影院", "剧院"], ["厨房", "餐厅"], ["寺庙", "道观"], ["夜市", "美食街"]],
  "Animals": [["熊猫", "北极熊"], ["猫", "狗"], ["老虎", "狮子"], ["兔子", "仓鼠"], ["青蛙", "蟾蜍"], ["蜜蜂", "蝴蝶"], ["海豚", "鲸鱼"], ["乌龟", "蜗牛"], ["麻雀", "燕子"], ["鸭子", "鹅"], ["狐狸", "狼"], ["螃蟹", "龙虾"]],
  "Wild card": [["春节", "中秋节"], ["红包", "礼物"], ["龙", "凤凰"], ["孙悟空", "哪吒"], ["财神", "月老"], ["武侠", "仙侠"], ["梦", "回忆"], ["太阳", "月亮"], ["雷声", "闪电"], ["秘密", "谣言"], ["魔术", "魔法"], ["运气", "实力"]],
  "Cozy things": [["奶茶", "热可可"], ["围巾", "手套"], ["毛毯", "棉被"], ["暖宝宝", "热水袋"], ["睡衣", "浴袍"], ["抱枕", "毛绒玩具"], ["午睡", "懒觉"], ["摇椅", "吊床"], ["香薰", "蜡烛"], ["相册", "日记"], ["童话", "摇篮曲"], ["泡澡", "泡脚"]],
  "Activities": [["麻将", "象棋"], ["乒乓球", "羽毛球"], ["唱歌", "跳舞"], ["书法", "画画"], ["剪纸", "折纸"], ["舞龙", "舞狮"], ["游泳", "潜水"], ["爬山", "露营"], ["跑步", "散步"], ["钓鱼", "捞鱼"], ["做饭", "烘焙"], ["猜谜", "脑筋急转弯"]],
  "Singapore treats": [["海南鸡饭", "烧鸭饭"], ["叻沙", "咖喱面"], ["咖椰吐司", "法式吐司"], ["辣椒螃蟹", "黑胡椒螃蟹"], ["肉骨茶", "猪肚汤"], ["炒粿条", "福建虾面"], ["豆花", "仙草"], ["煎蕊", "红豆冰"], ["咖喱角", "春卷"], ["榴莲", "菠萝蜜"], ["山竹", "红毛丹"], ["甘蔗汁", "椰子水"]]
};
const CHINESE_PACK_LABELS = { "Everyday": "日常生活", "Food": "美食", "Places": "地点", "Animals": "动物", "Wild card": "天马行空", "Cozy things": "温馨小物", "Activities": "活动", "Singapore treats": "新加坡美食", "My words": "我的词库" };
