// Built-in word packs. Each pair contains related but different clue words.
// Loaded before app.js and cached locally for offline play.
const DEFAULT_PAIRS = {
  "Everyday": [
    ["Coffee", "Tea"],
    ["Fork", "Spoon"],
    ["Shower", "Bath"],
    ["Shoes", "Slippers"],
    ["Pillow", "Blanket"],
    ["Phone", "Laptop"],
    ["Door", "Window"],
    ["Pen", "Pencil"],
    ["Soap", "Shampoo"],
    ["Towel", "Tissue"],
    ["Backpack", "Suitcase"],
    ["Wallet", "Purse"],
    ["Watch", "Clock"],
    ["Sofa", "Armchair"],
    ["Plate", "Bowl"],
    ["Cup", "Glass"],
    ["Broom", "Mop"],
    ["Fridge", "Freezer"],
    ["Oven", "Microwave"],
    ["Mirror", "Camera"],
    ["Curtains", "Blinds"],
    ["Key", "Password"],
    ["Stairs", "Lift"],
    ["Bicycle", "Scooter"],
    ["Bus", "Train"],
    ["Umbrella", "Raincoat"],
    ["Socks", "Gloves"],
    ["Notebook", "Diary"],
    ["Comb", "Hairbrush"],
    ["Candle", "Lamp"]
  ],
  "Food": [
    ["Pizza", "Burger"],
    ["Sushi", "Dumpling"],
    ["Pancake", "Waffle"],
    ["Ketchup", "Mustard"],
    ["Lemon", "Lime"],
    ["Cake", "Pie"],
    ["Rice", "Noodles"],
    ["Apple", "Pear"],
    ["Bread", "Toast"],
    ["Butter", "Cheese"],
    ["Honey", "Jam"],
    ["Chocolate", "Caramel"],
    ["Ice cream", "Frozen yogurt"],
    ["Cookie", "Brownie"],
    ["Muffin", "Cupcake"],
    ["Peach", "Apricot"],
    ["Strawberry", "Raspberry"],
    ["Watermelon", "Melon"],
    ["Potato", "Sweet potato"],
    ["Broccoli", "Cauliflower"],
    ["Carrot", "Radish"],
    ["Onion", "Garlic"],
    ["Peanut", "Almond"],
    ["Popcorn", "Potato chips"],
    ["Soup", "Stew"],
    ["Omelette", "Scrambled eggs"],
    ["Croissant", "Bagel"],
    ["Milkshake", "Smoothie"],
    ["Sausage", "Bacon"],
    ["Spaghetti", "Macaroni"]
  ],
  "Places": [
    ["Beach", "Pool"],
    ["School", "Office"],
    ["Airport", "Station"],
    ["Cinema", "Theatre"],
    ["Museum", "Library"],
    ["Hotel", "Hospital"],
    ["Zoo", "Aquarium"],
    ["Forest", "Jungle"],
    ["Cafe", "Restaurant"],
    ["Bakery", "Sweet shop"],
    ["Park", "Garden"],
    ["Mountain", "Hill"],
    ["Lake", "Pond"],
    ["River", "Canal"],
    ["Island", "Peninsula"],
    ["Village", "Town"],
    ["City", "Suburb"],
    ["Market", "Supermarket"],
    ["Castle", "Palace"],
    ["Cabin", "Cottage"],
    ["Bedroom", "Living room"],
    ["Kitchen", "Dining room"],
    ["Balcony", "Terrace"],
    ["Garage", "Car park"],
    ["Gym", "Stadium"],
    ["Farm", "Orchard"],
    ["Desert", "Savanna"],
    ["Cave", "Tunnel"],
    ["Harbour", "Marina"],
    ["Playground", "Theme park"]
  ],
  "Animals": [
    ["Cat", "Dog"],
    ["Lion", "Tiger"],
    ["Shark", "Dolphin"],
    ["Frog", "Toad"],
    ["Bee", "Wasp"],
    ["Rabbit", "Hamster"],
    ["Eagle", "Owl"],
    ["Crocodile", "Alligator"],
    ["Bear", "Panda"],
    ["Horse", "Donkey"],
    ["Sheep", "Goat"],
    ["Cow", "Buffalo"],
    ["Duck", "Goose"],
    ["Chicken", "Turkey"],
    ["Penguin", "Puffin"],
    ["Seal", "Sea lion"],
    ["Whale", "Orca"],
    ["Octopus", "Squid"],
    ["Crab", "Lobster"],
    ["Butterfly", "Moth"],
    ["Ant", "Termite"],
    ["Snail", "Slug"],
    ["Turtle", "Tortoise"],
    ["Lizard", "Gecko"],
    ["Wolf", "Fox"],
    ["Deer", "Moose"],
    ["Monkey", "Gorilla"],
    ["Squirrel", "Chipmunk"],
    ["Hedgehog", "Porcupine"],
    ["Zebra", "Giraffe"]
  ],
  "Wild card": [
    ["Moon", "Sun"],
    ["Wedding", "Funeral"],
    ["Dream", "Nightmare"],
    ["Hero", "Villain"],
    ["Rich", "Famous"],
    ["Ghost", "Zombie"],
    ["Past", "Future"],
    ["Truth", "Dare"],
    ["Magic", "Science"],
    ["Luck", "Skill"],
    ["Secret", "Rumour"],
    ["Wish", "Promise"],
    ["Treasure", "Prize"],
    ["King", "Queen"],
    ["Pirate", "Knight"],
    ["Detective", "Spy"],
    ["Robot", "Alien"],
    ["Mermaid", "Fairy"],
    ["Dragon", "Unicorn"],
    ["Adventure", "Holiday"],
    ["Birthday", "Anniversary"],
    ["Applause", "Cheering"],
    ["Whisper", "Murmur"],
    ["Shadow", "Reflection"],
    ["Sunrise", "Sunset"],
    ["Thunder", "Lightning"],
    ["Rainbow", "Aurora"],
    ["Puzzle", "Riddle"],
    ["Memory", "Imagination"],
    ["Freedom", "Privacy"]
  ],
  "Cozy things": [
    ["Teddy bear", "Plush bunny"],
    ["Duvet", "Quilt"],
    ["Beanbag", "Cushion"],
    ["Pyjamas", "Dressing gown"],
    ["Mittens", "Hand warmers"],
    ["Fireplace", "Heater"],
    ["Hot chocolate", "Warm milk"],
    ["Knitting", "Crochet"],
    ["Scrapbook", "Photo album"],
    ["Bookmark", "Book cover"],
    ["Fairy lights", "Lantern"],
    ["Nap", "Lie-in"],
    ["Picnic", "Barbecue"],
    ["Treehouse", "Tent"],
    ["Hammock", "Swing"],
    ["Music box", "Snow globe"],
    ["Sticker", "Stamp"],
    ["Ribbon", "Bow"],
    ["Yarn", "Thread"],
    ["Embroidery", "Cross stitch"],
    ["Teapot", "Kettle"],
    ["Bubble bath", "Foot bath"],
    ["Slipper socks", "Fuzzy slippers"],
    ["Rocking chair", "Porch swing"],
    ["Scented candle", "Incense"],
    ["Fluffy rug", "Bath mat"],
    ["Rain sounds", "Ocean sounds"],
    ["Bedtime story", "Lullaby"],
    ["Woolly hat", "Scarf"],
    ["Patchwork", "Quilting"]
  ],
  "Activities": [
    ["Swimming", "Diving"],
    ["Running", "Jogging"],
    ["Hiking", "Climbing"],
    ["Cycling", "Skating"],
    ["Skiing", "Snowboarding"],
    ["Surfing", "Paddleboarding"],
    ["Football", "Rugby"],
    ["Tennis", "Badminton"],
    ["Basketball", "Netball"],
    ["Bowling", "Golf"],
    ["Yoga", "Pilates"],
    ["Dancing", "Gymnastics"],
    ["Singing", "Humming"],
    ["Drawing", "Painting"],
    ["Reading", "Writing"],
    ["Cooking", "Baking"],
    ["Fishing", "Crabbing"],
    ["Camping", "Glamping"],
    ["Shopping", "Browsing"],
    ["Gardening", "Flower arranging"],
    ["Photography", "Filming"],
    ["Chess", "Checkers"],
    ["Hide and seek", "Tag"],
    ["Karaoke", "Concert"],
    ["Board game", "Card game"],
    ["Pottery", "Sculpting"],
    ["Juggling", "Magic tricks"],
    ["Origami", "Paper cutting"],
    ["Kayaking", "Canoeing"],
    ["Meditation", "Stretching"]
  ],
  "Singapore treats": [
    ["Kaya toast", "French toast"],
    ["Kopi", "Teh"],
    ["Laksa", "Curry noodles"],
    ["Chicken rice", "Duck rice"],
    ["Satay", "Kebab"],
    ["Roti prata", "Naan"],
    ["Nasi lemak", "Nasi briyani"],
    ["Char kway teow", "Hokkien mee"],
    ["Chilli crab", "Pepper crab"],
    ["Bak kut teh", "Beef soup"],
    ["Popiah", "Spring roll"],
    ["Chwee kueh", "Soon kueh"],
    ["Ondeh ondeh", "Mochi"],
    ["Ice kacang", "Chendol"],
    ["Tau huay", "Pudding"],
    ["Curry puff", "Samosa"],
    ["Fish ball", "Meatball"],
    ["Wanton mee", "Ban mian"],
    ["Mee rebus", "Mee siam"],
    ["Otah", "Fish cake"],
    ["Soya milk", "Almond milk"],
    ["Sugarcane juice", "Coconut water"],
    ["Bandung", "Rose tea"],
    ["Durian", "Jackfruit"],
    ["Mangosteen", "Rambutan"],
    ["Longan", "Lychee"],
    ["Pandan cake", "Butter cake"],
    ["Pineapple tart", "Jam tart"],
    ["Bee hoon", "Glass noodles"],
    ["Youtiao", "Churros"]
  ]
};
