// Built-in word packs. Each pair contains related but different clue words.
// Loaded before app.js and cached locally for offline play.
const DEFAULT_PAIRS = {
  "Everyday": [
    ["Coffee", "Tea"],
    ["Fork", "Spoon"],
    ["Shower", "Bath"],
    ["Shoes", "Slippers"],
    ["Pillow", "Blanket"],
    ["Phone", "Laptop"],
    ["Door", "Window"],
    ["Pen", "Pencil"],
    ["Soap", "Shampoo"],
    ["Towel", "Tissue"],
    ["Backpack", "Suitcase"],
    ["Wallet", "Purse"],
    ["Watch", "Clock"],
    ["Sofa", "Armchair"],
    ["Plate", "Bowl"],
    ["Cup", "Glass"],
    ["Broom", "Mop"],
    ["Fridge", "Freezer"],
    ["Oven", "Microwave"],
    ["Mirror", "Camera"],
    ["Curtains", "Blinds"],
    ["Key", "Password"],
    ["Stairs", "Lift"],
    ["Bicycle", "Scooter"],
    ["Bus", "Train"],
    ["Umbrella", "Raincoat"],
    ["Socks", "Gloves"],
    ["Notebook", "Diary"],
    ["Comb", "Hairbrush"],
    ["Candle", "Lamp"],
    ["Toothbrush", "Dental floss"],
    ["Washing machine", "Tumble dryer"],
    ["Fan", "Air conditioner"],
    ["Vacuum cleaner", "Dustpan"],
    ["Stapler", "Paper clip"],
    ["Scissors", "Craft knife"],
    ["Glue", "Sticky tape"],
    ["Remote control", "Game controller"],
    ["Headphones", "Earbuds"],
    ["Charger", "Power bank"],
    ["Alarm clock", "Doorbell"],
    ["Calendar", "Planner"],
    ["Envelope", "Postcard"],
    ["Helmet", "Seat belt"],
    ["Cap", "Sun hat"],
    ["Jeans", "Shorts"],
    ["Shirt", "T-shirt"],
    ["Jacket", "Coat"],
    ["Ring", "Bracelet"],
    ["Bucket", "Watering can"]
  ],
  "Food": [
    ["Pizza", "Burger"],
    ["Sushi", "Dumpling"],
    ["Pancake", "Waffle"],
    ["Ketchup", "Mustard"],
    ["Lemon", "Lime"],
    ["Cake", "Pie"],
    ["Rice", "Noodles"],
    ["Apple", "Pear"],
    ["Bread", "Toast"],
    ["Butter", "Cheese"],
    ["Honey", "Jam"],
    ["Chocolate", "Caramel"],
    ["Ice cream", "Frozen yogurt"],
    ["Cookie", "Brownie"],
    ["Muffin", "Cupcake"],
    ["Peach", "Apricot"],
    ["Strawberry", "Raspberry"],
    ["Watermelon", "Honeydew"],
    ["Potato", "Sweet potato"],
    ["Broccoli", "Cauliflower"],
    ["Carrot", "Radish"],
    ["Onion", "Garlic"],
    ["Peanut", "Almond"],
    ["Popcorn", "Potato chips"],
    ["Soup", "Stew"],
    ["Omelette", "Scrambled eggs"],
    ["Croissant", "Bagel"],
    ["Milkshake", "Smoothie"],
    ["Sausage", "Bacon"],
    ["Spaghetti", "Macaroni"],
    ["Mango", "Papaya"],
    ["Orange", "Grapefruit"],
    ["Grape", "Blueberry"],
    ["Pineapple", "Kiwi"],
    ["Cucumber", "Zucchini"],
    ["Spinach", "Lettuce"],
    ["Cabbage", "Kale"],
    ["Pumpkin", "Squash"],
    ["Tomato", "Bell pepper"],
    ["Cinnamon", "Ginger"],
    ["Salt", "Sugar"],
    ["Soy sauce", "Vinegar"],
    ["Tofu", "Tempeh"],
    ["Salmon", "Tuna"],
    ["Steak", "Pork chop"],
    ["Fried chicken", "Chicken nuggets"],
    ["Burrito", "Taco"],
    ["Lasagna", "Ravioli"],
    ["Cheesecake", "Tiramisu"],
    ["Custard", "Jelly"]
  ],
  "Places": [
    ["Beach", "Pool"],
    ["School", "Office"],
    ["Airport", "Station"],
    ["Cinema", "Theatre"],
    ["Museum", "Library"],
    ["Hotel", "Hospital"],
    ["Zoo", "Aquarium"],
    ["Forest", "Jungle"],
    ["Cafe", "Restaurant"],
    ["Bakery", "Sweet shop"],
    ["Park", "Garden"],
    ["Mountain", "Hill"],
    ["Lake", "Pond"],
    ["River", "Canal"],
    ["Island", "Peninsula"],
    ["Village", "Town"],
    ["City", "Suburb"],
    ["Market", "Supermarket"],
    ["Castle", "Palace"],
    ["Cabin", "Cottage"],
    ["Bedroom", "Living room"],
    ["Kitchen", "Dining room"],
    ["Balcony", "Terrace"],
    ["Garage", "Car park"],
    ["Gym", "Stadium"],
    ["Farm", "Orchard"],
    ["Desert", "Savanna"],
    ["Cave", "Tunnel"],
    ["Harbour", "Marina"],
    ["Playground", "Theme park"],
    ["Bookshop", "Toy shop"],
    ["Pharmacy", "Clinic"],
    ["Post office", "Bank"],
    ["Barber shop", "Hair salon"],
    ["Police station", "Fire station"],
    ["Laundromat", "Dry cleaner"],
    ["Bus stop", "Taxi stand"],
    ["Crossroads", "Roundabout"],
    ["Bridge", "Overpass"],
    ["Waterfall", "Fountain"],
    ["Meadow", "Field"],
    ["Greenhouse", "Plant nursery"],
    ["Campsite", "Holiday resort"],
    ["Hostel", "Guesthouse"],
    ["Attic", "Basement"],
    ["Hallway", "Lobby"],
    ["Classroom", "Lecture hall"],
    ["Laboratory", "Workshop"],
    ["Skate park", "Ice rink"],
    ["Food court", "Hawker centre"]
  ],
  "Animals": [
    ["Cat", "Dog"],
    ["Lion", "Tiger"],
    ["Shark", "Dolphin"],
    ["Frog", "Toad"],
    ["Bee", "Wasp"],
    ["Rabbit", "Hamster"],
    ["Eagle", "Owl"],
    ["Crocodile", "Alligator"],
    ["Grizzly bear", "Panda"],
    ["Horse", "Donkey"],
    ["Sheep", "Goat"],
    ["Cow", "Buffalo"],
    ["Duck", "Goose"],
    ["Chicken", "Turkey"],
    ["Penguin", "Puffin"],
    ["Seal", "Sea lion"],
    ["Blue whale", "Orca"],
    ["Octopus", "Squid"],
    ["Crab", "Lobster"],
    ["Butterfly", "Moth"],
    ["Ant", "Termite"],
    ["Snail", "Slug"],
    ["Turtle", "Tortoise"],
    ["Iguana", "Gecko"],
    ["Wolf", "Fox"],
    ["Deer", "Moose"],
    ["Monkey", "Gorilla"],
    ["Squirrel", "Chipmunk"],
    ["Hedgehog", "Porcupine"],
    ["Zebra", "Giraffe"],
    ["Elephant", "Rhinoceros"],
    ["Hippopotamus", "Walrus"],
    ["Leopard", "Cheetah"],
    ["Llama", "Alpaca"],
    ["Camel", "Llama"],
    ["Kangaroo", "Wallaby"],
    ["Otter", "Beaver"],
    ["Raccoon", "Badger"],
    ["Meerkat", "Mongoose"],
    ["Parrot", "Parakeet"],
    ["Swan", "Flamingo"],
    ["Peacock", "Pheasant"],
    ["Crow", "Raven"],
    ["Pigeon", "Dove"],
    ["Pelican", "Stork"],
    ["Goldfish", "Koi"],
    ["Seahorse", "Starfish"],
    ["Stingray", "Swordfish"],
    ["Grasshopper", "Cricket"],
    ["Ladybird", "Firefly"]
  ],
  "Wild card": [
    ["Moon", "Sun"],
    ["Wedding", "Funeral"],
    ["Dream", "Nightmare"],
    ["Hero", "Villain"],
    ["Rich", "Famous"],
    ["Ghost", "Zombie"],
    ["Past", "Future"],
    ["Truth", "Dare"],
    ["Magic", "Science"],
    ["Luck", "Skill"],
    ["Secret", "Rumour"],
    ["Wish", "Promise"],
    ["Treasure", "Prize"],
    ["King", "Queen"],
    ["Pirate", "Knight"],
    ["Detective", "Spy"],
    ["Robot", "Alien"],
    ["Mermaid", "Fairy"],
    ["Dragon", "Unicorn"],
    ["Adventure", "Holiday"],
    ["Birthday", "Anniversary"],
    ["Applause", "Cheering"],
    ["Whisper", "Murmur"],
    ["Shadow", "Reflection"],
    ["Sunrise", "Sunset"],
    ["Thunder", "Lightning"],
    ["Rainbow", "Aurora"],
    ["Puzzle", "Riddle"],
    ["Memory", "Imagination"],
    ["Freedom", "Privacy"],
    ["Courage", "Confidence"],
    ["Patience", "Persistence"],
    ["Jealousy", "Envy"],
    ["Surprise", "Shock"],
    ["Victory", "Celebration"],
    ["Competition", "Cooperation"],
    ["Friendship", "Romance"],
    ["Tradition", "Habit"],
    ["Legend", "Myth"],
    ["Superhero", "Wizard"],
    ["Vampire", "Werewolf"],
    ["Ninja", "Samurai"],
    ["Crown", "Tiara"],
    ["Medal", "Trophy"],
    ["Map", "Compass"],
    ["Time machine", "Teleportation"],
    ["Invisible", "Immortal"],
    ["Gravity", "Magnetism"],
    ["Echo", "Silence"],
    ["Blizzard", "Sandstorm"]
  ],
  "Cozy things": [
    ["Teddy bear", "Plush bunny"],
    ["Duvet", "Quilt"],
    ["Beanbag", "Cushion"],
    ["Pyjamas", "Dressing gown"],
    ["Mittens", "Hand warmers"],
    ["Fireplace", "Heater"],
    ["Hot chocolate", "Warm milk"],
    ["Knitting", "Crochet"],
    ["Scrapbook", "Photo album"],
    ["Bookmark", "Book cover"],
    ["Fairy lights", "Lantern"],
    ["Nap", "Lie-in"],
    ["Picnic", "Barbecue"],
    ["Treehouse", "Tent"],
    ["Hammock", "Swing"],
    ["Music box", "Snow globe"],
    ["Sticker", "Stamp"],
    ["Ribbon", "Bow"],
    ["Yarn", "Thread"],
    ["Embroidery", "Cross stitch"],
    ["Teapot", "Kettle"],
    ["Bubble bath", "Foot bath"],
    ["Slipper socks", "Fuzzy slippers"],
    ["Rocking chair", "Porch swing"],
    ["Scented candle", "Incense"],
    ["Fluffy rug", "Bath mat"],
    ["Rain sounds", "Ocean sounds"],
    ["Bedtime story", "Lullaby"],
    ["Woolly hat", "Scarf"],
    ["Patchwork", "Quilting"],
    ["Sourdough", "Banana bread"],
    ["Apple crumble", "Bread pudding"],
    ["Herbal tea", "Chai"],
    ["Cinnamon roll", "Doughnut"],
    ["Reading nook", "Window seat"],
    ["Camping chair", "Deck chair"],
    ["Flannel", "Fleece"],
    ["Cardigan", "Sweater"],
    ["Nightlight", "Lava lamp"],
    ["Cuddling", "Holding hands"],
    ["Cat purring", "Birdsong"],
    ["Wind chime", "Singing bowl"],
    ["Dried flowers", "Pressed flowers"],
    ["Houseplant", "Terrarium"],
    ["Handwritten letter", "Greeting card"],
    ["Colouring book", "Sketchbook"],
    ["Jigsaw puzzle", "Model kit"],
    ["Sleep mask", "Earplugs"],
    ["Essential oil", "Room spray"],
    ["Breakfast in bed", "Afternoon tea"]
  ],
  "Activities": [
    ["Swimming", "Diving"],
    ["Running", "Jogging"],
    ["Hiking", "Climbing"],
    ["Cycling", "Skating"],
    ["Skiing", "Snowboarding"],
    ["Surfing", "Paddleboarding"],
    ["Football", "Rugby"],
    ["Tennis", "Badminton"],
    ["Basketball", "Netball"],
    ["Bowling", "Golf"],
    ["Yoga", "Pilates"],
    ["Dancing", "Gymnastics"],
    ["Singing", "Humming"],
    ["Drawing", "Painting"],
    ["Reading", "Writing"],
    ["Cooking", "Baking"],
    ["Fishing", "Crabbing"],
    ["Camping", "Glamping"],
    ["Shopping", "Browsing"],
    ["Gardening", "Flower arranging"],
    ["Photography", "Filming"],
    ["Chess", "Checkers"],
    ["Hide and seek", "Tag"],
    ["Karaoke", "Concert"],
    ["Board game", "Card game"],
    ["Pottery", "Sculpting"],
    ["Juggling", "Magic tricks"],
    ["Origami", "Paper cutting"],
    ["Kayaking", "Canoeing"],
    ["Meditation", "Stretching"],
    ["Table tennis", "Squash"],
    ["Volleyball", "Handball"],
    ["Baseball", "Cricket"],
    ["Boxing", "Wrestling"],
    ["Karate", "Taekwondo"],
    ["Fencing", "Archery"],
    ["Horse riding", "Dog walking"],
    ["Ice skating", "Roller skating"],
    ["Skateboarding", "Rollerblading"],
    ["Sailing", "Rowing"],
    ["Snorkelling", "Scuba diving"],
    ["Birdwatching", "Stargazing"],
    ["Collecting coins", "Collecting stamps"],
    ["Solving sudoku", "Doing crosswords"],
    ["Building sandcastles", "Making snowmen"],
    ["Flying a kite", "Blowing bubbles"],
    ["Playing piano", "Playing guitar"],
    ["Acting", "Storytelling"],
    ["Volunteering", "Fundraising"],
    ["Road trip", "Train journey"]
  ],
  "Singapore treats": [
    ["Kaya toast", "French toast"],
    ["Kopi", "Teh"],
    ["Laksa", "Curry noodles"],
    ["Chicken rice", "Duck rice"],
    ["Satay", "Kebab"],
    ["Roti prata", "Naan"],
    ["Nasi lemak", "Nasi briyani"],
    ["Char kway teow", "Hokkien mee"],
    ["Chilli crab", "Pepper crab"],
    ["Bak kut teh", "Beef soup"],
    ["Popiah", "Spring roll"],
    ["Chwee kueh", "Soon kueh"],
    ["Ondeh ondeh", "Mochi"],
    ["Ice kacang", "Chendol"],
    ["Tau huay", "Pudding"],
    ["Curry puff", "Samosa"],
    ["Fish ball", "Meatball"],
    ["Wanton mee", "Ban mian"],
    ["Mee rebus", "Mee siam"],
    ["Otah", "Fish cake"],
    ["Soya milk", "Almond milk"],
    ["Sugarcane juice", "Coconut water"],
    ["Bandung", "Rose tea"],
    ["Durian", "Jackfruit"],
    ["Mangosteen", "Rambutan"],
    ["Longan", "Lychee"],
    ["Pandan cake", "Butter cake"],
    ["Pineapple tart", "Jam tart"],
    ["Bee hoon", "Glass noodles"],
    ["Youtiao", "Churros"],
    ["Carrot cake", "Oyster omelette"],
    ["Fish head curry", "Curry chicken"],
    ["Nasi padang", "Economy rice"],
    ["Mee goreng", "Maggi goreng"],
    ["Murtabak", "Egg prata"],
    ["Appam", "Thosai"],
    ["Putu piring", "Kueh tutu"],
    ["Ang ku kueh", "Kueh lapis"],
    ["Pulut hitam", "Bubur cha cha"],
    ["Cheng tng", "Tang yuan"],
    ["Tau suan", "Red bean soup"],
    ["Fish soup", "Yong tau foo"],
    ["Prawn mee", "Lor mee"],
    ["Bak chor mee", "Minced meat rice"],
    ["Roast pork", "Char siu"],
    ["Sambal stingray", "Grilled squid"],
    ["Cockles", "Clams"],
    ["Prawn cracker", "Fish cracker"],
    ["Kopi peng", "Teh peng"],
    ["Milo dinosaur", "Milo Godzilla"]
  ]
};

// Independently curated Simplified Chinese packs; keys match the English categories.
const CHINESE_PAIRS = {
  "Everyday": [
    ["牙刷", "牙膏"],
    ["拖鞋", "凉鞋"],
    ["雨伞", "雨衣"],
    ["冰箱", "空调"],
    ["洗衣机", "烘干机"],
    ["电饭锅", "高压锅"],
    ["筷子", "勺子"],
    ["枕头", "被子"],
    ["书包", "行李箱"],
    ["手机", "平板电脑"],
    ["钥匙", "门卡"],
    ["扫把", "拖把"],
    ["洗发水", "护发素"],
    ["肥皂", "沐浴露"],
    ["镜子", "相机"],
    ["闹钟", "手表"],
    ["台灯", "手电筒"],
    ["窗帘", "百叶窗"],
    ["眼镜", "墨镜"],
    ["衬衫", "T恤"],
    ["牛仔裤", "运动裤"],
    ["帽子", "头盔"],
    ["手提包", "双肩包"],
    ["钱包", "零钱包"],
    ["剪刀", "美工刀"],
    ["胶水", "胶带"],
    ["订书机", "回形针"],
    ["笔记本", "日记本"],
    ["钢笔", "铅笔"],
    ["橡皮", "修正带"],
    ["遥控器", "游戏手柄"],
    ["耳机", "音箱"],
    ["充电器", "充电宝"],
    ["水壶", "保温杯"],
    ["盘子", "碗"],
    ["平底锅", "炒锅"],
    ["垃圾桶", "回收箱"],
    ["电梯", "扶梯"],
    ["沙发", "躺椅"],
    ["床垫", "榻榻米"]
  ],
  "Food": [
    ["包子", "馒头"],
    ["饺子", "馄饨"],
    ["豆浆", "牛奶"],
    ["火锅", "麻辣烫"],
    ["油条", "麻花"],
    ["汤圆", "元宵"],
    ["粽子", "月饼"],
    ["烧卖", "小笼包"],
    ["米饭", "粥"],
    ["煎饼", "葱油饼"],
    ["红豆", "绿豆"],
    ["红薯", "土豆"],
    ["豆腐", "豆干"],
    ["蛋糕", "面包"],
    ["曲奇", "夹心饼干"],
    ["麻薯", "年糕"],
    ["冰淇淋", "酸奶"],
    ["芝士", "黄油"],
    ["花生", "核桃"],
    ["杏仁", "腰果"],
    ["苹果", "梨"],
    ["桃子", "杏"],
    ["草莓", "蓝莓"],
    ["葡萄", "樱桃"],
    ["西瓜", "哈密瓜"],
    ["芒果", "木瓜"],
    ["香蕉", "菠萝"],
    ["黄瓜", "丝瓜"],
    ["茄子", "西葫芦"],
    ["菠菜", "生菜"],
    ["卷心菜", "白菜"],
    ["西兰花", "菜花"],
    ["胡萝卜", "白萝卜"],
    ["洋葱", "大葱"],
    ["姜", "蒜"],
    ["酱油", "醋"],
    ["糖", "盐"],
    ["炸鸡", "烤鸭"],
    ["牛排", "猪排"],
    ["面条", "米线"]
  ],
  "Places": [
    ["茶馆", "咖啡馆"],
    ["菜市场", "超市"],
    ["故宫", "长城"],
    ["学校", "图书馆"],
    ["动物园", "水族馆"],
    ["海边", "游泳池"],
    ["公园", "花园"],
    ["机场", "火车站"],
    ["电影院", "剧院"],
    ["厨房", "餐厅"],
    ["寺庙", "道观"],
    ["夜市", "美食街"],
    ["医院", "诊所"],
    ["宾馆", "民宿"],
    ["小区", "村庄"],
    ["客厅", "卧室"],
    ["阳台", "天台"],
    ["车库", "停车场"],
    ["操场", "体育馆"],
    ["健身房", "游乐场"],
    ["博物馆", "美术馆"],
    ["书店", "文具店"],
    ["面包店", "甜品店"],
    ["理发店", "美容院"],
    ["邮局", "银行"],
    ["警察局", "消防站"],
    ["公交站", "地铁站"],
    ["码头", "港口"],
    ["森林", "竹林"],
    ["草原", "沙漠"],
    ["湖泊", "池塘"],
    ["河流", "运河"],
    ["山洞", "隧道"],
    ["山顶", "山谷"],
    ["瀑布", "喷泉"],
    ["海岛", "半岛"],
    ["农场", "果园"],
    ["温室", "花圃"],
    ["露营地", "度假村"],
    ["城堡", "宫殿"]
  ],
  "Animals": [
    ["熊猫", "北极熊"],
    ["猫", "狗"],
    ["老虎", "狮子"],
    ["兔子", "仓鼠"],
    ["青蛙", "蟾蜍"],
    ["蜜蜂", "蝴蝶"],
    ["海豚", "鲸鱼"],
    ["乌龟", "蜗牛"],
    ["麻雀", "燕子"],
    ["鸭子", "鹅"],
    ["狐狸", "狼"],
    ["螃蟹", "龙虾"],
    ["大象", "犀牛"],
    ["河马", "海象"],
    ["豹子", "猎豹"],
    ["骆驼", "羊驼"],
    ["绵羊", "山羊"],
    ["马", "驴"],
    ["奶牛", "水牛"],
    ["猪", "野猪"],
    ["鸡", "火鸡"],
    ["孔雀", "火烈鸟"],
    ["企鹅", "海鸥"],
    ["鹦鹉", "八哥"],
    ["老鹰", "猫头鹰"],
    ["乌鸦", "喜鹊"],
    ["鸽子", "斑鸠"],
    ["天鹅", "仙鹤"],
    ["海豹", "海狮"],
    ["章鱼", "鱿鱼"],
    ["金鱼", "锦鲤"],
    ["海马", "海星"],
    ["海胆", "水母"],
    ["蚂蚁", "白蚁"],
    ["瓢虫", "萤火虫"],
    ["蚱蜢", "蟋蟀"],
    ["蛇", "鳄鱼"],
    ["刺猬", "豪猪"],
    ["松鼠", "花栗鼠"],
    ["猴子", "大猩猩"]
  ],
  "Wild card": [
    ["春节", "中秋节"],
    ["红包", "礼物"],
    ["龙", "凤凰"],
    ["孙悟空", "哪吒"],
    ["财神", "月老"],
    ["武侠", "仙侠"],
    ["梦", "回忆"],
    ["太阳", "月亮"],
    ["雷声", "闪电"],
    ["秘密", "谣言"],
    ["魔术", "魔法"],
    ["运气", "实力"],
    ["端午节", "元宵节"],
    ["生日", "纪念日"],
    ["婚礼", "毕业典礼"],
    ["英雄", "反派"],
    ["海盗", "骑士"],
    ["侦探", "间谍"],
    ["机器人", "外星人"],
    ["美人鱼", "精灵"],
    ["吸血鬼", "狼人"],
    ["隐身", "变身"],
    ["穿越", "时光倒流"],
    ["未来", "过去"],
    ["彩虹", "极光"],
    ["日出", "日落"],
    ["影子", "倒影"],
    ["回声", "寂静"],
    ["奖牌", "奖杯"],
    ["皇冠", "头饰"],
    ["地图", "指南针"],
    ["宝藏", "宝石"],
    ["愿望", "承诺"],
    ["友情", "爱情"],
    ["勇气", "自信"],
    ["耐心", "毅力"],
    ["惊喜", "惊吓"],
    ["竞争", "合作"],
    ["传奇", "神话"],
    ["自由", "隐私"]
  ],
  "Cozy things": [
    ["奶茶", "热可可"],
    ["围巾", "手套"],
    ["毛毯", "棉被"],
    ["暖宝宝", "热水袋"],
    ["睡衣", "浴袍"],
    ["抱枕", "毛绒玩具"],
    ["午睡", "懒觉"],
    ["摇椅", "吊床"],
    ["香薰", "蜡烛"],
    ["相册", "日记"],
    ["童话", "摇篮曲"],
    ["泡澡", "泡脚"],
    ["毛衣", "开衫"],
    ["棉袜", "毛拖鞋"],
    ["睡帽", "眼罩"],
    ["热牛奶", "姜茶"],
    ["红糖水", "蜂蜜水"],
    ["烤红薯", "烤栗子"],
    ["桂花糕", "红豆糕"],
    ["小蛋糕", "松饼"],
    ["火炉", "暖气"],
    ["落地灯", "小夜灯"],
    ["灯笼", "串灯"],
    ["风铃", "八音盒"],
    ["抱抱", "牵手"],
    ["猫咪呼噜", "鸟鸣"],
    ["雨声", "海浪声"],
    ["窗边座椅", "阅读角"],
    ["藤椅", "懒人沙发"],
    ["地毯", "地垫"],
    ["桌布", "餐垫"],
    ["编织", "刺绣"],
    ["毛线", "布料"],
    ["贴纸", "印章"],
    ["丝带", "蝴蝶结"],
    ["书签", "书套"],
    ["明信片", "手写信"],
    ["干花", "压花"],
    ["多肉", "苔藓"],
    ["拼图", "积木"]
  ],
  "Activities": [
    ["麻将", "象棋"],
    ["乒乓球", "羽毛球"],
    ["唱歌", "跳舞"],
    ["书法", "画画"],
    ["剪纸", "折纸"],
    ["舞龙", "舞狮"],
    ["游泳", "潜水"],
    ["爬山", "露营"],
    ["跑步", "散步"],
    ["钓鱼", "捞鱼"],
    ["做饭", "烘焙"],
    ["猜谜", "脑筋急转弯"],
    ["足球", "篮球"],
    ["排球", "手球"],
    ["网球", "壁球"],
    ["棒球", "板球"],
    ["滑冰", "轮滑"],
    ["双板滑雪", "单板滑雪"],
    ["冲浪", "桨板"],
    ["划船", "皮划艇"],
    ["骑车", "滑板"],
    ["射箭", "击剑"],
    ["拳击", "摔跤"],
    ["瑜伽", "普拉提"],
    ["跳绳", "踢毽子"],
    ["跳房子", "丢沙包"],
    ["捉迷藏", "抓人游戏"],
    ["放风筝", "吹泡泡"],
    ["堆沙堡", "堆雪人"],
    ["弹钢琴", "弹吉他"],
    ["听音乐", "看电影"],
    ["读书", "写作"],
    ["摄影", "拍视频"],
    ["园艺", "插花"],
    ["做陶艺", "捏橡皮泥"],
    ["逛街", "网购"],
    ["下围棋", "玩五子棋"],
    ["打桌游", "玩纸牌"],
    ["观鸟", "看星星"],
    ["泡温泉", "做按摩"]
  ],
  "Singapore treats": [
    ["海南鸡饭", "烧鸭饭"],
    ["叻沙", "咖喱面"],
    ["咖椰吐司", "法式吐司"],
    ["辣椒螃蟹", "黑胡椒螃蟹"],
    ["肉骨茶", "猪肚汤"],
    ["炒粿条", "福建虾面"],
    ["豆花", "仙草"],
    ["煎蕊", "红豆冰"],
    ["咖喱角", "春卷"],
    ["榴莲", "菠萝蜜"],
    ["山竹", "红毛丹"],
    ["甘蔗汁", "椰子水"],
    ["沙爹", "烤肉串"],
    ["印度煎饼", "印度烤饼"],
    ["椰浆饭", "黄姜饭"],
    ["水粿", "笋粿"],
    ["蚝煎", "菜头粿"],
    ["马来炒面", "印度炒面"],
    ["云吞面", "板面"],
    ["虾面", "卤面"],
    ["米粉", "粉丝"],
    ["肉脞面", "肉脞饭"],
    ["酿豆腐", "鱼汤"],
    ["烧肉", "叉烧"],
    ["咖啡", "奶茶"],
    ["冰咖啡", "冰奶茶"],
    ["美禄恐龙", "美禄哥斯拉"],
    ["玫瑰奶", "水果茶"],
    ["豆奶", "杏仁奶"],
    ["龙眼", "荔枝"],
    ["香兰蛋糕", "牛油蛋糕"],
    ["黄梨挞", "蛋挞"],
    ["咖喱鱼头", "咖喱鸡"],
    ["参巴魔鬼鱼", "烤鱿鱼"],
    ["乌打", "鱼饼"],
    ["鱼丸", "肉丸"],
    ["椰丝球", "糯米糕"],
    ["龟苓膏", "凉粉"],
    ["摩摩喳喳", "黑糯米粥"],
    ["绿豆爽", "红豆汤"]
  ]
};
const CHINESE_PACK_LABELS = { "Everyday": "日常生活", "Food": "美食", "Places": "地点", "Animals": "动物", "Wild card": "天马行空", "Cozy things": "温馨小物", "Activities": "活动", "Singapore treats": "新加坡美食", "My words": "我的词库" };
